# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/motorctrl/motorctrl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl || ORIG_REF_NAME==motorctrl}]

# IP: bd/motorctrl/ip/motorctrl_processing_system7_0_0/motorctrl_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_processing_system7_0_0 || ORIG_REF_NAME==motorctrl_processing_system7_0_0}]

# IP: bd/motorctrl/ip/motorctrl_xadc_wiz_0_0/motorctrl_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_xadc_wiz_0_0 || ORIG_REF_NAME==motorctrl_xadc_wiz_0_0}]

# IP: bd/motorctrl/ip/motorctrl_ps7_0_axi_periph_0/motorctrl_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_ps7_0_axi_periph_0 || ORIG_REF_NAME==motorctrl_ps7_0_axi_periph_0}]

# IP: bd/motorctrl/ip/motorctrl_rst_ps7_0_100M_0/motorctrl_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_rst_ps7_0_100M_0 || ORIG_REF_NAME==motorctrl_rst_ps7_0_100M_0}]

# IP: bd/motorctrl/ip/motorctrl_xlconstant_0_0/motorctrl_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_xlconstant_0_0 || ORIG_REF_NAME==motorctrl_xlconstant_0_0}]

# IP: bd/motorctrl/ip/motorctrl_axi_gpio_0_0/motorctrl_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_axi_gpio_0_0 || ORIG_REF_NAME==motorctrl_axi_gpio_0_0}]

# IP: bd/motorctrl/ip/motorctrl_xbar_0/motorctrl_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_xbar_0 || ORIG_REF_NAME==motorctrl_xbar_0}]

# IP: bd/motorctrl/ip/motorctrl_axi_gpio_1_1/motorctrl_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_axi_gpio_1_1 || ORIG_REF_NAME==motorctrl_axi_gpio_1_1}]

# IP: bd/motorctrl/ip/motorctrl_PWM_0_0/motorctrl_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_PWM_0_0 || ORIG_REF_NAME==motorctrl_PWM_0_0}]

# IP: bd/motorctrl/ip/motorctrl_StateController_0_0/motorctrl_StateController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_StateController_0_0 || ORIG_REF_NAME==motorctrl_StateController_0_0}]

# IP: bd/motorctrl/ip/motorctrl_PI_CTRL_0_0/motorctrl_PI_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_PI_CTRL_0_0 || ORIG_REF_NAME==motorctrl_PI_CTRL_0_0}]

# IP: bd/motorctrl/ip/motorctrl_auto_pc_0/motorctrl_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motorctrl_auto_pc_0 || ORIG_REF_NAME==motorctrl_auto_pc_0}]

# XDC: bd/motorctrl/motorctrl_ooc.xdc
