# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GITES/MotorControl/MotorControl.cache/wt [current_project]
set_property parent.project_path D:/GITES/MotorControl/MotorControl.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  d:/GITES/ip_repo/PI_CTRL_1.0
  d:/GITES/ip_repo/StateController_1.0
  d:/GITES/ip_repo/PWM_1.0
} [current_project]
set_property ip_output_repo d:/GITES/MotorControl/MotorControl.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/hdl/motorctrl_wrapper.vhd
add_files D:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/motorctrl.bd
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_processing_system7_0_0/motorctrl_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_xadc_wiz_0_0/motorctrl_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_xadc_wiz_0_0/motorctrl_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_rst_ps7_0_100M_0/motorctrl_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_rst_ps7_0_100M_0/motorctrl_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_rst_ps7_0_100M_0/motorctrl_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_axi_gpio_0_0/motorctrl_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_axi_gpio_0_0/motorctrl_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_axi_gpio_0_0/motorctrl_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_xbar_0/motorctrl_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_axi_gpio_1_1/motorctrl_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_axi_gpio_1_1/motorctrl_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_axi_gpio_1_1/motorctrl_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/ip/motorctrl_auto_pc_0/motorctrl_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/motorctrl_ooc.xdc]
set_property is_locked true [get_files D:/GITES/MotorControl/MotorControl.srcs/sources_1/bd/motorctrl/motorctrl.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GITES/MotorControl/MotorControl.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files D:/GITES/MotorControl/MotorControl.srcs/constrs_1/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top motorctrl_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef motorctrl_wrapper.dcp

catch { report_utilization -file motorctrl_wrapper_utilization_synth.rpt -pb motorctrl_wrapper_utilization_synth.pb }
